name: build-website
run-name: Build website
on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"

jobs:
  build-web:
    name: "Build for Web"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Gradle build for web
        run: ./gradlew wasmJsBrowserDistribution
      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: Website-resource-folder
          path: './composeApp/build/dist/wasmJs/productionExecutable/'
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: './composeApp/build/dist/wasmJs/productionExecutable/'
          branch: gh-pages
          clean-exclude: |
            README.md
            .gitignore

